LOGLEVELDEBUG = -1
LOGLEVELINFO = -2
LOGLEVELWARNING = -3
LOGLEVELERROR = -4
LOGLEVELCRITICAL = -5

__all__ = [
    "LOGLEVELDEBUG",
    "LOGLEVELINFO",
    "LOGLEVELWARNING",
    "LOGLEVELERROR",
    "LOGLEVELCRITICAL"
]